# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: No rights reserved

version = 1

[[annotations]]
path = ["**.desktop.in.in", "**.service.in", "**.json", "**.po", "**.pot"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Andy Holmes <andrew.g.r.holmes@gmail.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [".github/**", ".gitignore", ".gitmodules", "build-aux/**", "CHANGELOG.md", "CONTRIBUTING.md", "README.md", "**.jpg", "**.ontology", "**.png", "**.svg", "**.vcf", "**.wrap"]
precedence = "aggregate"
SPDX-FileCopyrightText = "No rights reserved"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["help/*.page", "help/*.tmpl", "help/*/legal.xml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Andy Holmes <andrew.g.r.holmes@gmail.com>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "src/plugins/findmyphone/data/alert.oga"
precedence = "aggregate"
SPDX-FileCopyrightText = "Red Hat, Inc."
SPDX-License-Identifier = "CC-BY-SA-3.0"
SPDX-FileComment = "Created by Richard Hughes"

